interface ZIF_CMA_PARCELSCDS_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZCMA_PARCELSCDS,
 CREATE_ZCMA_PARCELSCDS         TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA71283465C23DE',
 DELETE_ZCMA_PARCELSCDS         TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA71283465CA3DE',
 LOCK_ZCMA_PARCELSCDS           TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA71283465B63DE',
 SAVE_ZCMA_PARCELSCDS           TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA71283465D23DE',
 UNLOCK_ZCMA_PARCELSCDS         TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA71283465BA3DE',
 UPDATE_ZCMA_PARCELSCDS         TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA71283465C63DE',
 VALIDATE_ZCMA_PARCELSCDS       TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA71283465CE3DE',
      END OF ZCMA_PARCELSCDS,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZCMA_PARCELSCDS,
        BEGIN OF LOCK_ZCMA_PARCELSCDS,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZCMA_PARCELSCDS,
        BEGIN OF UNLOCK_ZCMA_PARCELSCDS,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZCMA_PARCELSCDS,
      END OF ZCMA_PARCELSCDS,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZCMA_PARCELSCDS,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '0E0D2133B95F1EDA9AA712A6438583DE',
      END OF ZCMA_PARCELSCDS,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZCMA_PARCELSCDS,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA71283465B43DE',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA71283465B03DE',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA71283465C03DE',
      END OF ZCMA_PARCELSCDS,
      BEGIN OF ZCMA_PARCELSCDS_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA71283465D83DE',
      END OF ZCMA_PARCELSCDS_LOCK,
      BEGIN OF ZCMA_PARCELSCDS_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA71283465D63DE',
      END OF ZCMA_PARCELSCDS_MESSAGE,
      BEGIN OF ZCMA_PARCELSCDS_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA71283465DA3DE',
      END OF ZCMA_PARCELSCDS_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZCMA_PARCELSCDS,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZCMA_PARCELSCDS,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '0E0D2133B95F1EDA9AA71283465A63DE' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZCMA_PARCELSCDS' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZCMA_PARCELSCDS,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '0E0D2133B95F1EDA9AA712A64385A3DE',
      END OF ZCMA_PARCELSCDS,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZCMA_PARCELSCDS                TYPE /BOBF/OBM_GROUP_KEY VALUE '0E0D2133B95F1EDA9AA712A6438D03DE',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZCMA_PARCELSCDS                TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA9AA71283465AA3DE',
 ZCMA_PARCELSCDS_LOCK           TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA9AA71283465B23DE',
 ZCMA_PARCELSCDS_MESSAGE        TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA9AA71283465AE3DE',
 ZCMA_PARCELSCDS_PROPERTY       TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA9AA71283465BE3DE',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZCMA_PARCELSCDS,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  ACC_ID                         TYPE STRING VALUE 'ACC_ID',
  PARCEL_ID                      TYPE STRING VALUE 'PARCEL_ID',
  CUSTOMER                       TYPE STRING VALUE 'CUSTOMER',
  PARCEL_NO                      TYPE STRING VALUE 'PARCEL_NO',
  VALUE                          TYPE STRING VALUE 'VALUE',
  CURR_CODE                      TYPE STRING VALUE 'CURR_CODE',
  DUE_DATE                       TYPE STRING VALUE 'DUE_DATE',
  STATUS                         TYPE STRING VALUE 'STATUS',
  PAID_DATE                      TYPE STRING VALUE 'PAID_DATE',
  CREA_DATE_TIME                 TYPE STRING VALUE 'CREA_DATE_TIME',
  CREA_UNAME                     TYPE STRING VALUE 'CREA_UNAME',
  LCHG_DATE_TIME                 TYPE STRING VALUE 'LCHG_DATE_TIME',
  LCHG_UNAME                     TYPE STRING VALUE 'LCHG_UNAME',
      END OF ZCMA_PARCELSCDS,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZCMA_PARCELSCDS,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '0E0D2133B95F1EDA9AA71283465AC3DE',
      END OF ZCMA_PARCELSCDS,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZCMA_PARCELSCDS,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE '0E0D2133B95F1EDA9AA712A6438603DE',
      END OF ZCMA_PARCELSCDS,
    END OF SC_VALIDATION .
endinterface.
