interface ZIF_CMA_DEPARTMENT_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ROOT,
 CREATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA99F6B859592021B5',
 DELETE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA99F6B8595920A1B5',
 LOCK_ROOT                      TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA99F6B859591F61B5',
 SAVE_ROOT                      TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA99F6B859592121B5',
 UNLOCK_ROOT                    TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA99F6B859591FA1B5',
 UPDATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA99F6B859592061B5',
 VALIDATE_ROOT                  TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA99F6B8595920E1B5',
      END OF ROOT,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ROOT,
        BEGIN OF LOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ROOT,
        BEGIN OF UNLOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ROOT,
      END OF ROOT,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ROOT,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA99F6B859591F41B5',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA99F6B859591F01B5',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA99F6B859592001B5',
      END OF ROOT,
      BEGIN OF ROOT_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA99F6B859592181B5',
      END OF ROOT_LOCK,
      BEGIN OF ROOT_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA99F6B859592161B5',
      END OF ROOT_MESSAGE,
      BEGIN OF ROOT_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA99F6B8595921A1B5',
      END OF ROOT_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ROOT,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ROOT,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '0E0D2133B95F1EDA99F69FF1EDAF41B3' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZCMA_DEPARTMENT' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ROOT                           TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA99F6B859591EA1B5',
 ROOT_LOCK                      TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA99F6B859591F21B5',
 ROOT_MESSAGE                   TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA99F6B859591EE1B5',
 ROOT_PROPERTY                  TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA99F6B859591FE1B5',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ROOT,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  DEPARTMENT_ID                  TYPE STRING VALUE 'DEPARTMENT_ID',
  NAME                           TYPE STRING VALUE 'NAME',
  SUPERVISOR                     TYPE STRING VALUE 'SUPERVISOR',
      END OF ROOT,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ROOT,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '0E0D2133B95F1EDA99F6B859591EC1B5',
      END OF ROOT,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_QUERY,
      BEGIN OF ROOT,
 SELECT_ALL                     TYPE /BOBF/OBM_QUERY_KEY VALUE '0E0D2133B95F1EDA99F6B8595921C1B5',
 SELECT_BY_ELEMENTS             TYPE /BOBF/OBM_QUERY_KEY VALUE '0E0D2133B95F1EDA99F6B8595921E1B5',
      END OF ROOT,
    END OF SC_QUERY .
  constants:
    BEGIN OF SC_QUERY_ATTRIBUTE,
      BEGIN OF ROOT,
        BEGIN OF SELECT_BY_ELEMENTS,
 KEY                            TYPE STRING VALUE 'KEY',
 PARENT_KEY                     TYPE STRING VALUE 'PARENT_KEY',
 ROOT_KEY                       TYPE STRING VALUE 'ROOT_KEY',
 NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
 DEPARTMENT_ID                  TYPE STRING VALUE 'DEPARTMENT_ID',
 NAME                           TYPE STRING VALUE 'NAME',
 SUPERVISOR                     TYPE STRING VALUE 'SUPERVISOR',
        END OF SELECT_BY_ELEMENTS,
      END OF ROOT,
    END OF SC_QUERY_ATTRIBUTE .
endinterface.
