interface ZIF_CMA_ACCOUNTSRECEIVABLECD_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZCMA_ACCOUNTSRECEIVABLECDS,
 CREATE_ZCMA_ACCOUNTSRECEIVABLE TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA7121507ED43DE',
 DELETE_ZCMA_ACCOUNTSRECEIVABLE TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA7121507EDC3DE',
 LOCK_ZCMA_ACCOUNTSRECEIVABLECD TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA7121507EC83DE',
 SAVE_ZCMA_ACCOUNTSRECEIVABLECD TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA7121507EE43DE',
 UNLOCK_ZCMA_ACCOUNTSRECEIVABLE TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA7121507ECC3DE',
 UPDATE_ZCMA_ACCOUNTSRECEIVABLE TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA7121507ED83DE',
 VALIDATE_ZCMA_ACCOUNTSRECEIVAB TYPE /BOBF/ACT_KEY VALUE '0E0D2133B95F1EDA9AA7121507EE03DE',
      END OF ZCMA_ACCOUNTSRECEIVABLECDS,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZCMA_ACCOUNTSRECEIVABLECDS,
        BEGIN OF LOCK_ZCMA_ACCOUNTSRECEIVABLECD,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZCMA_ACCOUNTSRECEIVABLECD,
        BEGIN OF UNLOCK_ZCMA_ACCOUNTSRECEIVABLE,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZCMA_ACCOUNTSRECEIVABLE,
      END OF ZCMA_ACCOUNTSRECEIVABLECDS,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZCMA_ACCOUNTSRECEIVABLECDS,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '0E0D2133B95F1EDA9AA7121507EF23DE',
      END OF ZCMA_ACCOUNTSRECEIVABLECDS,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZCMA_ACCOUNTSRECEIVABLECDS,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA7121507EC63DE',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA7121507EC23DE',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA7121507ED23DE',
      END OF ZCMA_ACCOUNTSRECEIVABLECDS,
      BEGIN OF ZCMA_ACCOUNTSRECEIVABLECDS_LOC,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA7121507EEA3DE',
      END OF ZCMA_ACCOUNTSRECEIVABLECDS_LOC,
      BEGIN OF ZCMA_ACCOUNTSRECEIVABLECDS_MES,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA7121507EE83DE',
      END OF ZCMA_ACCOUNTSRECEIVABLECDS_MES,
      BEGIN OF ZCMA_ACCOUNTSRECEIVABLECDS_PRO,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0E0D2133B95F1EDA9AA7121507EEC3DE',
      END OF ZCMA_ACCOUNTSRECEIVABLECDS_PRO,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZCMA_ACCOUNTSRECEIVABLECDS,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZCMA_ACCOUNTSRECEIVABLECDS,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '0E0D2133B95F1EDA9AA7121507EB83DE' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZCMA_ACCOUNTSRECEIVABLECDS' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZCMA_ACCOUNTSRECEIVABLECDS,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '0E0D2133B95F1EDA9AA7121507EF43DE',
      END OF ZCMA_ACCOUNTSRECEIVABLECDS,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZCMA_ACCOUNTSRECEIVABLECDS     TYPE /BOBF/OBM_GROUP_KEY VALUE '0E0D2133B95F1EDA9AA7121507F3E3DE',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZCMA_ACCOUNTSRECEIVABLECDS     TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA9AA7121507EBC3DE',
 ZCMA_ACCOUNTSRECEIVABLECDS_LOC TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA9AA7121507EC43DE',
 ZCMA_ACCOUNTSRECEIVABLECDS_MES TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA9AA7121507EC03DE',
 ZCMA_ACCOUNTSRECEIVABLECDS_PRO TYPE /BOBF/OBM_NODE_KEY VALUE '0E0D2133B95F1EDA9AA7121507ED03DE',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZCMA_ACCOUNTSRECEIVABLECDS,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  ID                             TYPE STRING VALUE 'ID',
  NF                             TYPE STRING VALUE 'NF',
  CREA_DATE_TIME                 TYPE STRING VALUE 'CREA_DATE_TIME',
  CREA_UNAME                     TYPE STRING VALUE 'CREA_UNAME',
  LCHG_DATE_TIME                 TYPE STRING VALUE 'LCHG_DATE_TIME',
  LCHG_UNAME                     TYPE STRING VALUE 'LCHG_UNAME',
      END OF ZCMA_ACCOUNTSRECEIVABLECDS,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZCMA_ACCOUNTSRECEIVABLECDS,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '0E0D2133B95F1EDA9AA7121507EBE3DE',
      END OF ZCMA_ACCOUNTSRECEIVABLECDS,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZCMA_ACCOUNTSRECEIVABLECDS,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE '0E0D2133B95F1EDA9AA7121507EF83DE',
      END OF ZCMA_ACCOUNTSRECEIVABLECDS,
    END OF SC_VALIDATION .
endinterface.
